name: Docker testing
run-name: Docker testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  CHECK: "mark"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - uses: actions/checkout@master

      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: test123
          file: Dockerfile
          context: .
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
